### PR TITLE
Add workspace file for testing against multiple versions

### PR DESCRIPTION
**Pull request by rgrinberg**
make all-supported-ocaml-versions build & tests against 4.03.0, 4.04.2, 4.05.0, 4.06.0

### CODE REVIEW

**Comment by hannesm** [comment]
something similar used to be in the `lwt` repository (where then `jbuilder build` always failed for me).  since different people name their switches differently, IMHO the workspaces do not belong into version control.

**Comment by rgrinberg** [comment]
Note that this wouldn't cause any failures outside of using this target. The issue with hard coding switch names is a bit annoying of course, I'd be interested in ways of improving it if possible.

**Comment by hannesm** [comment]
ok, then it was differently setup in lwt.  nevertheless, I don't think having this (completely unused, since our CI systems work differently -- there is one job per OCaml version) in the repository is a good idea.

**Comment by rgrinberg** [comment]
There are many targets in the Makefile that are unused by the CI. Nevertheless, if the the maintainers don't end up using this target then of course it will be redundant and unmaintained, and eventually harmful. So yeah, if there's no interest from the other maintainers then it's best to close this.

**Comment by samoht** [comment]
Yea, I am not sure about that workspace thing as well. Closing (but could be happy to re-open later if more maintainers are interested).

**Pull request closed without merging**
