### PR TITLE
follow-up on #155

### PR DESCRIPTION
**Pull request by samoht**
/cc @avsm

### CODE REVIEW

**Comment by avsm** [comment]
lgtm if we figure out why it passed on travis before ;-)

**Comment by djs55** [comment]
I think we've forgotten to include  build-test` (or similar) in any of the `.opam` files :/ (Or have I missed something?)

**Comment by djs55** [comment]
Oh no, I was wrong -- `ppx_cstruct` has one

**Comment by samoht** [comment]
Good catch, I've added the tests for `cstruct` too.

```
$ find . -name jbuild | xargs grep runtest
./lib_test/jbuild: ((name   runtest)
./lib_test/jbuild: ((name   runtest)
./ppx_test/jbuild: ((name   runtest)
./ppx_test/jbuild: ((name   runtest)
./ppx_test/jbuild: ((name   runtest)
./ppx_test/with-lwt/jbuild:; ((name   runtest)
./ppx_test/with-sexp/jbuild: ((name   runtest)
```

**Comment by samoht** [comment]
All green!

**Pull request merged**
