### PR TITLE
Javascript packaging fixes

### PR DESCRIPTION
**Pull request by jonludlam**

### CODE REVIEW

**Comment by jonludlam** [comment]
I'm not totally sure of the second patch - there are indications upstream that the javascript stubs are moving, but I'm not sure of the reasoning - https://github.com/ocsigen/js_of_ocaml/commit/7c1c8cff90712f6df67026ba7349941ae7ebf603#diff-6f8d707ac8ba0276a5f94701eb821566

**Comment by avsm** [comment]
I was *just* wondering what the random `js/` directory that @djs55 added a few years ago was for, and here comes this patch :-)

**Comment by avsm** [comment]
is there any way to have a testcase for this that could do something without a browser around?

**Comment by jonludlam** [comment]
Yes - as long as we've got node around.

**Comment by avsm** [comment]
sure -- could not hook this into the full test case and just run it manually before a release

**Comment by avsm** [comment]
(and in CI)

**Comment by emillon** [comment]
This will take care of #203. It looks like we could test this a bit by making a tiny js_of_ocaml project? (that wouldn't execute the code, but at least this can make sure that we can link everything properly)

**Comment by emillon** [comment]
(but if the function names are not checked by `js_of_ocaml`, maybe it's not useful)

**Comment by avsm** [comment]
The fix is right -- can do the testcase as a separate PR

**Pull request merged**
