### PR TITLE
Fix pre-4.07 code generation with stdlib-shims

### PR DESCRIPTION
**Pull request by avsm**

### CODE REVIEW

**Comment by hannesm** [comment]
(fwiw I had this in https://github.com/mirage/ocaml-cstruct/pull/269/commits/a7f16b39f3e9e2282ba5b403d3dcc1d5c8779173)

**Comment by avsm** [comment]
I merged that -- this is a followon patch to add stdlib-shims to the _ppx runtime_ deps list, so that it's picked up by generated code as well.  I didn't catch that as ppx_cstruct tests weren't running before either.

**Comment by hannesm** [comment]
ok, what I meant: the change to the dune file in the ppx directory was already present in the commit a7f16b3 -- but it seems to not have survived a merge/rebase. no worries, this seems to be good to be merged (apart from CI failures). thanks for cutting (and re-cutting) the release! :)

**Comment by avsm** [comment]
I don't think this change was present -- https://github.com/mirage/ocaml-cstruct/commit/a7f16b39f3e9e2282ba5b403d3dcc1d5c8779173 modified `(libraries)` but not `(ppx_runtime_libraries)`.  I'll double check the changes are merge errors are obviously a bad thing :-)

**Comment by avsm** [comment]
The test errors are due to #263

**Comment by hannesm** [comment]
oh, I was not aware of ppx_runtime_libraries, sorry for the noise

**Comment by avsm** [comment]
No worries; I appreciate the review! I've pushed d696925a70a65dbc3316e77eaee28e1d7bee8623 to fix the tests and will merge/release again when CI is green

**Pull request merged**
