### PR TITLE
Update jsoo runtime with missing primitives

### PR DESCRIPTION
**Pull request by hhugo**
and use optimized blit functions provided by jsoo.

One should wait for the 3 jsoo PR to be merged and released first.
- [x] https://github.com/ocsigen/js_of_ocaml/pull/879
- [x] https://github.com/ocsigen/js_of_ocaml/pull/883
- [x] https://github.com/ocsigen/js_of_ocaml/pull/884

### CODE REVIEW

**Comment by XVilka** [comment]
Fist was merged, last two were closed (cancelled?).

**Comment by hhugo** [comment]
Everything was merged

**Comment by dinosaure** [comment]
I will happy to merge but I have some concerns about retro-compatibility. If I use `< js_of_ocaml.3.4` and `cstruct` with your PR, from what I see about OPAM file, both can be installed (`cstruct` does not depend on `js_of_ocaml`), `cstruct` will compile properly?

**Comment by hhugo** [comment]
Yes, one probably need to add a constraint in opam

**Comment by avsm** [comment]
constraint added in d6d858a6fa1899f7af7c0db35937f1a599aad037, thanks

**Pull request merged**
