### PR TITLE
port to jbuilder

### PR DESCRIPTION
**Pull request by avsm**
still need to do ppx and hook in tests, and ensure both standalone ppx work.

This PR does the work of splitting up PPX into several packages which are all standalone and independently installable through OPAM, so the core `cstruct` will not depend on ppx or lwt or async.

cc @rgrinberg

### CODE REVIEW

**Comment by rgrinberg** [comment]
@avsm Mind letting me push on this branch? I'd like to proceed with this.

**Comment by avsm** [comment]
Go for it!

**Comment by rgrinberg** [comment]
@avsm OK I got some progress on this. I think you forgot to let me push on this branch though.

**Comment by rgrinberg** [comment]
Things left to do
- [ ] what to do with cstruct.js? does it needs its own cstruct package? E.g. cstruct-js
- [ ] test out ppx compat. omp + classical ppx

cc @samoht @let-def

**Comment by rgrinberg** [comment]
@let-def tested this work with ocamlbuild and jbuilder. no need to test but you can still have a glance if you'd like

**Comment by rgrinberg** [comment]
@samoht @avsm for cstruct.js I just elected to keep everything the same and make it a part of cstruct directly. If there's a for these js stubs to have their dependencies, we can split it into its own package then.

I think this port to jbuilder is ready, so we can remove the WIP from the title and consider this for merging.

**Comment by avsm** [comment]
Awesome, thanks @rgrinberg! I'll use this PR to setup a revdeps test on the cstruct repo to help with the upper bounds.

**Comment by samoht** [comment]
Can you please rebase? I'll cut a release without jbuilder and then we can make a new release with jbuilder in.

**Comment by rgrinberg** [comment]
Rebased @samoht

**Comment by avsm** [comment]
Just debugging travis...

**Pull request merged**
