### PR TITLE
Add shiftv

### PR DESCRIPTION
**Pull request by talex5**
This is particularly useful for advancing an iovec.

### CODE REVIEW

**Review by dinosaure — APPROVED** [review]

**Review by avsm — APPROVED** [review]
Looks right to me. @djs55 you had dstruct or something similar to work with lists of cstructs didn't you? Does this overlap with that?

**Comment by talex5** [comment]
CI was failing (on master too). I've updated the opam metadata... I think I've found the magic combination that makes all the CIs happy!

**Comment by dinosaure** [comment]
I'm ok to merge, do you want a release soon?

**Comment by talex5** [comment]
A release would be nice at some point, but for now I've just inlined a copy in my code.

**Comment by dinosaure** [comment]
Ok, will do a minor one tomorrow :+1:.

**Comment by talex5** [comment]
Thanks!

**Pull request merged**
