### PR TITLE
Just testing bun; do not merge!

### PR DESCRIPTION
**Pull request by talex5**

### CODE REVIEW

**Comment by talex5** [comment]
Drone build passed! https://cloud.drone.io/mirage/ocaml-cstruct/24

bun did report `It's likely that this job could benefit from more fuzzing time`, which seems a bit odd as it also reported `Pending paths : 0 faves, 0 total`.

**Comment by avsm** [comment]
The build always passes now -- it's just not clear to me if it's doing anything useful due to the stats being 0.  We could introduce a bug into a PR and see if the fuzzer catches it!

**Comment by talex5** [comment]
Pinning my `bun#lwt` branch, the stats aren't zero:

```
Total run time : 1 days, 10 hours
Total execs : 416 million
Cumulative speed : 139897 execs/sec
```

But yes, introducing a bug would be a good idea.

**Comment by avsm** [comment]
I could just push a bin of your lwt branch to the #255 branch and then merge the new CI, if you're happy with your fix. We can roll that back to a released bun at a later stage.

**Comment by avsm** [comment]
(I'm working on the basis that some fuzzing is better than no fuzzing in CI)

**Comment by talex5** [comment]
Re-adding a bug...

**Comment by talex5** [comment]
With #249 reverted, it correctly finds the bug:

```
Summary stats
=============
Fuzzers alive : 48
Total run time : 0 days, 0 hours
Total execs : 12 million
Cumulative speed : 185747 execs/sec
Pending paths : 0 faves, 2348 total
Pending per fuzzer : 0 faves, 48 total (on average)
Crashes found : 0 locally unique
17:24.20:Fuzzer 17 (pid=33555) finished
Crashes found! Take a look; copy/paste to save for reproduction:
echo zADo/////////789Ojo6OjoA////ABL///8FADo6Ojr8/Pz79f8= | base64 -d > crash_0.$(date -u +%s)
```

```
$ ./_build/default/fuzz/fuzz.exe crash_0.1555608453 
BE.set_uint64: ....
fish: “./_build/default/fuzz/fuzz.exe…” terminated by signal SIGSEGV (Address boundary error)
```

**Comment by talex5** [comment]
@yomimono has now merged https://github.com/yomimono/ocaml-bun/pull/7, so I think it should work if you just rebuild your PR.

**Pull request closed without merging**
