### PR TITLE
Travis skeleton

### PR DESCRIPTION
**Pull request by dsheets**
A couple fixups over #55 so (hopefully) the tests pass.

### CODE REVIEW

**Comment by dsheets** [comment]
I don't appear to have rights to unwedge <https://travis-ci.org/mirage/ocaml-cstruct/jobs/56554780>. The other fixes are in the pipeline e.g. dsheets/ocaml-dns@a931b6f39c10d05b6425f6f1be2ac932e1806d40

**Comment by avsm** [comment]
Restarted

**Comment by dsheets** [comment]
This now requires ocaml/opam-repository#3861 and ocaml/opam-repository#3862 to pass.

**Comment by dsheets** [comment]
Scratch that, Travis file now contains the constraints as well.

**Comment by avsm** [comment]
we could release this despite the upstream breaks, since they are all constraint failures.  It'll be easier to test those by breaking the cycle.

**Pull request merged**
