### PR TITLE
PPX support, take 2 

### PR DESCRIPTION
**Pull request by avsm**

### CODE REVIEW

**Comment by avsm** [comment]
Turns out I can create PRs from @drup's braches too :)

**Comment by Drup** [comment]
Ah well, that works too. To be honest, I just tried a bit @nojb's branch for fun, found bugs, solved them. I don't plan on dedicating a lot more time to it in the near future.

**Comment by hannesm** [comment]
I can't find an example of how a `cenum` should be defined using ppx.  From the older PR:

```
[%%cenum
type message_type =
    | DH_COMMIT [@id 2]
    | DATA [@id 3]
    | DH_KEY [@id 0x0a]
    | REVEAL_SIGNATURE [@id 0x11]
    | SIGNATURE [@id 0x12]
  [@@uint8_t] [@@sexp]
]
```

doesn't work, ```
File "_none_", line 1:
Error: This variant expression is expected to have type message_type
       The constructor None does not belong to type message_type
```

any hints?

**Comment by nojb** [comment]
Hi Hannes,

I think you discovered a bug in `ppx_cstruct`.  The following patch should solve the problem.
(Unfortunately I don't have time at the moment to try it myself.)

Cheers,
Nicolas

```diff
diff --git a/ppx/ppx_cstruct.ml b/ppx/ppx_cstruct.ml
index e6a781f..636080c 100644
--- a/ppx/ppx_cstruct.ml
+++ b/ppx/ppx_cstruct.ml
@@ -320,7 +320,7 @@ let output_enum _loc name fields width ~sexp =
   let printers = List.map (fun ({txt = f},_) ->
       {pc_lhs = Ast.pconstr f []; pc_guard = None; pc_rhs = Ast.str f}) fields in
   let parsers = List.map (fun ({txt = f},_) ->
-      {pc_lhs = Ast.pstr f; pc_guard = None; pc_rhs = Ast.constr f []}) fields in
+      {pc_lhs = Ast.pstr f; pc_guard = None; pc_rhs = Ast.constr "Some" [Ast.constr f []]}) fields in
   let getter {txt = x} = sprintf "int_to_%s" x in
   let setter {txt = x} = sprintf "%s_to_int" x in
   let printer {txt = x} = sprintf "%s_to_string" x in
```

**Comment by hannesm** [comment]
thx, your patch works for me... I opened #81 with your diff

**Pull request merged**
