### PR TITLE
Add a deprecation on Cstruct.len (use Cstruct.length instead)

### PR DESCRIPTION
**Pull request by dinosaure**
According to #282 to be ready (and to not forget) for a possible next release.

### CODE REVIEW

**Comment by hannesm** [comment]
is the predicate `deprecated` or `ocaml.deprecated`? i.e. does the above result in a deprecation warning? (I so far used `@@ocaml.deprecated`).

**Comment by dinosaure** [comment]
According to [the official documentation](https://caml.inria.fr/pub/docs/manual-ocaml/attributes.html#ss%3Abuiltin-attributes), both can be used, but I can prepend with `ocaml` if you want.

**Comment by hannesm** [comment]
@dinosaure thanks, I tested this locally, and it works great. I enabled OCaml-CI on this repository. Good to merge once CI (should we remove travis?) are finished.

**Review by hannesm — APPROVED** [review]

**Comment by dinosaure** [comment]
The CI fails on the linter about `ppx/dune` which is not the part of this PR but the linter was running on this file in #285. To avoid conflict, I will not push a pass of `ocamlformat` on this file.

About Travis CI, I prefer to be conservative on CIs or we should open an issue to discuss about that.

**Comment by hannesm** [comment]
> travis

I read this morning https://github.com/ocaml/ocaml-ci-scripts/issues/353 -- and I don't see a good reason to use travis in this repository (given that github actions and ocaml-ci are doing a good job :)

> The CI fails on the linter about ppx/dune which is not the part of this PR but the linter was running on this file in #285.

fine with me to fix that CI issue in a different PR :) good to merge this PR from my side.

**Pull request merged**
