### PR TITLE
Add missing dependency on ppx_tools_versioned

### PR DESCRIPTION
**Pull request by let-def**
This shoud fix the build with latest ppx_tools_versioned.

### CODE REVIEW

**Comment by let-def** [comment]
(Without affecting the build with previous versions)

**Comment by let-def** [comment]
The first fix was not fixing the root cause...
It is simply a dependency on `ppx_tools_versioned` that is missing. It used to be provided by `ppx_tools_versioned.metaquot`, but that was an unnecessary dependency that was removed in latest version.

**Comment by rgrinberg** [comment]
@avsm or @samoht would it be possible to merge and release this already? I see this annoying quite a few users.

**Comment by samoht** [comment]
Ok I'll do that today.

**Comment by samoht** [comment]
Merging now: I'll fix the CI issues in an upcoming PR.

**Pull request merged**
