### PR TITLE
Remove camlp4: from now on we're ppx only

### PR DESCRIPTION
**Pull request by djs55**
Following discussion on #mirage today, the plan is to release a new
cstruct with ppx only and fix the reverse dependencies.

Signed-off-by: David Scott <dave.scott@docker.com>

### CODE REVIEW

**Comment by djs55** [comment]
Unfortunately this doesn't build and I don't know why. The error is:
```
File "ppx_test/basic.ml", line 17, characters 3-10:
Uninterpreted extension 'cstruct'.
Command exited with code 2.
```
If I run the ppx manually it looks ok:
```
$ ocamlc -dsource -ppx ./_build/ppx/ppx_cstruct.native ppx_test/basic.ml 
let sizeof_foo = 15
let get_foo_a v = Cstruct.get_uint8 v 0
let set_foo_a v x = Cstruct.set_uint8 v 0 x
...
```

In the _oasis file I have:
```
Executable test_ppx
  Build$:       flag(tests) && flag(ppx)
  Install:      false
  Path:         ppx_test
  Custom:       true
  CompiledObject: best
  BuildTools:   ppx_cstruct
  BuildDepends: cstruct, unix, oUnit, cstruct.unix
  MainIs:       tests.ml
```
-- I thought I just needed the `BuildTools`. Clearly my _oasis skills are not up to scratch.

Does anyone know what I'm doing wrong? This is my first use of ppx. /cc @samoht @hannesm :)

**Comment by hannesm** [comment]
sorry, no. ended up with the same problem, but decided to not move testing to oasis back then (left it in `./test.sh`)... a solution would be great to have!

**Comment by djs55** [comment]
OK, that's good to know. I guess we could keep the `test.sh` or if feeling adventurous, drop oasis and replace with make/ocamlbuild?

**Comment by dbuenzli** [comment]
> drop oasis and replace with make/ocamlbuild?

This usually leads to very poor packaging, with the package failing to build in various contexts (windows, byte-code only switches, etc.).

**Comment by rgrinberg** [comment]
What about ocamlbuild + topkg?

**Comment by djs55** [comment]
I think this extra tag fixes my problem:
```
diff --git a/_tags b/_tags
index 39708c9..ba5b419 100644
--- a/_tags
+++ b/_tags
@@ -116,3 +116,4 @@ true: annot, bin_annot
 <lib_test/tests.{native,byte}>: custom
 # OASIS_STOP
 true: annot, bin_annot, debug, principal
+<ppx_test/*.ml>: ppx(ppx_cstruct)
```
(Phew, no need to make major build changes!)

**Comment by dbuenzli** [comment]
> What about ocamlbuild + topkg?

Wait a bit (timeframe 1-3 weeks).

**Comment by djs55** [comment]
It looks like the revdeps failed as expected:
```
#=== ERROR while installing mirage-profile.0.6.1 ==============================#
# opam-version         1.2.2 (2dee5d69c0bd29731e6cb2ee537f0adf72404ba4)
# os                   linux
# command              ./configure --prefix /home/opam/.opam/system --disable-xen
# path                 /home/opam/.opam/system/build/mirage-profile.0.6.1
# compiler             system (4.01.0)
# exit-code            1
# env-file             /home/opam/.opam/system/build/mirage-profile.0.6.1/mirage-profile-4700-777834.env
# stdout-file          /home/opam/.opam/system/build/mirage-profile.0.6.1/mirage-profile-4700-777834.out
# stderr-file          /home/opam/.opam/system/build/mirage-profile.0.6.1/mirage-profile-4700-777834.err
### stderr ###
# ocamlfind: Package `cstruct.syntax' not found
# W: Field 'pkg_cstruct_syntax' is not set: Command ''/home/opam/.opam/system/bin/ocamlfind' query -format %d cstruct.syntax > '/tmp/oasis-dd92be.txt'' terminated with error code 2
# E: Cannot find findlib package cstruct.syntax
# E: Failure("1 configuration error")
```
@samoht shall we go ahead and merge, and start working on fixing the revdeps?

**Comment by djs55** [comment]
Related to [mirage/mirage-profile#17]

**Comment by samoht** [comment]
> @samoht shall we go ahead and merge, and start working on fixing the revdeps?

I think that better to put version constraints in the repo first, so they use the previous version of ctype (can add PACKAGE=cstruct.<the new version>` in the travis file to be sure this is not picked.

**Comment by djs55** [comment]
Related to [ocaml/opam-repository#5986]

**Comment by hannesm** [comment]
afaics you can also remove the type_conv dependency (to really get rid of camlp4), which was only needed for cstruct.syntax.  great work!

**Comment by djs55** [comment]
Right, I think all the references to `type_conv` and `camlp4` are gone (except for a note in the README.md which says the last version with cstruct.syntax was v1.9.0)

**Comment by djs55** [comment]
CentOS 6 failed with a missing depext: (a known issue with CentOS itself)
```
Determining fastest mirrors
 * base: mirror.cs.uwp.edu
 * extras: centos.mirrors.tds.net
 * updates: centos.chicago.waneq.com
No package xen-devel available.
```

**Pull request merged**
