### PR TITLE
rerelease 1.6.0

### PR DESCRIPTION
**Pull request by avsm**
Also fixes for sexp test compilation

### CODE REVIEW

**Comment by samoht** [comment]
The tests need to be hooked in the Travis scripts (currently it just calls `./test`). A good fix would be to compile all the tests in `_oasis` directly.

**Comment by avsm** [comment]
See #55 for test fixups

**Comment by samoht** [comment]
@avsm need to call the new s-exp test in test.sh as well

**Comment by avsm** [comment]
Why? Both are being run independently, and we're phasing out test.sh

**Comment by samoht** [comment]
@avsm because if you look at https://github.com/mirage/ocaml-cstruct/blob/master/opam#L24 you'll see that (1) we call "configure" again which is useless and more importantly (2) we only call `./test.sh` in the tests. So either we should call `make test` there, or we should add the test into `test.sh` so it will be run by Travis.

**Pull request merged**
