### PR TITLE
don't depend hard on type_conv

### PR DESCRIPTION
**Pull request by hannesm**
attempt at fixing #84

### CODE REVIEW

**Comment by hannesm** [comment]
what now fails are the reverse dependencies, who expect that depending on cstruct will give them cstruct.syntax -- whereas they need to depend on type_conv + camlp4 (actually, type_conv is sufficient since it depends on camlp4).  any opinions? should we fix up all the cstruct.syntax users? @avsm @samoht others?

**Comment by samoht** [comment]
I didn't know that we had `cstruct.syntax` user actually :-)
A possibility is to add a virtual `cstruct-syntax` package and use this explicitly in the constraints instead of some magic `camlp4+type_conv` incantations.

**Comment by samoht** [comment]
or actually, just adding version constraints to existing users of `cstruct.syntax` should be enough...

**Comment by hannesm** [comment]
@samoht well, tcpip, dns, ... all use `cenum` and `cstruct` p4 extension. adding a `cstruct-syntax` package sounds like a good idea

**Comment by hannesm** [comment]
a version constraint would not be a good solution imho, since cstruct keeps to provide that sub-package if you have type_conv and camlp4 installed...

**Comment by avsm** [comment]
> a version constraint would not be a good solution imho, since cstruct keeps to provide that sub-package if you have type_conv and camlp4 installed...

hm yeah, we want to propagate additional dependencies...

**Comment by avsm** [comment]
> A possibility is to add a virtual cstruct-syntax package and use this explicitly in the constraints instead of some magic camlp4+type_conv incantations.

Yes, I prefer this solution... reducing the depopts (and especially combinations of them) is the way to go...

**Comment by hannesm** [comment]
but virtual packages feel very hackish as well.. esp since you might need to version bump them at arbitrary points (and people tend to forget this during release processes - see mirage-types/mirage-types-lwt in opam-repo)... I'd actually use the type_conv instead of camlp4 depopt, since type_conv depends on camlp4 anyways (or just stick with both camlp4 and type_conv)

**Comment by hannesm** [comment]
superseeded by #95 I believe

**Pull request closed without merging**
